version: "3.9"

services:
  pgdatabase:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "policedb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password1"
    volumes:
      - "F:/test/database:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - airflow


networks:
  airflow:
    external:
      name: data_ingestion_project_2_default